/// <reference lib="DOM" /> 
export * from './ShadowMaterial.d.ts';
export * from './SpriteMaterial.d.ts';
export * from './RawShaderMaterial.d.ts';
export * from './ShaderMaterial.d.ts';
export * from './PointsMaterial.d.ts';
export * from './MeshPhysicalMaterial.d.ts';
export * from './MeshStandardMaterial.d.ts';
export * from './MeshPhongMaterial.d.ts';
export * from './MeshToonMaterial.d.ts';
export * from './MeshNormalMaterial.d.ts';
export * from './MeshLambertMaterial.d.ts';
export * from './MeshDepthMaterial.d.ts';
export * from './MeshDistanceMaterial.d.ts';
export * from './MeshBasicMaterial.d.ts';
export * from './MeshMatcapMaterial.d.ts';
export * from './LineDashedMaterial.d.ts';
export * from './LineBasicMaterial.d.ts';
export * from './Material.d.ts';
